- hosts: all
  become: true
  tasks:
     - name: Install httpd
       yum:
         name: httpd
         state: present

     - name: start httpd
       service:
          name: httpd
          stated: started
          enabled: yes

     - name: Allow on Firewall
       firewalld:
          service: http
          permanent: yes
          immediate: yes
          state: enabled

     - name: edit doc page
       lineinfile:
          path: /var/www/html/index.html
          line: "This is my playbook"
          create: yes
         tags: http

     - name: Test the web
       shell: curl localhost
       tags: http

            
