- hosts: Node1
  become: yes
  tasks:
    - name: Install NFS-UTILS
      yum:
        name: nfs-utils
        state: latest
      ignore_errors: yes

    - name: start service
      service:
         name: nfs-server
         state: started
         enabled: yes

- hosts: all
  become: yes
  tasks:
    - name: Install tree
      yum: name=tree state=present
